export const GET_NEW_STORIES_SUCCESS = "GET_NEW_STORIES_SUCCESS";
export const GET_NEW_STORIES_FAILURE = "GET_NEW_STORIES_FAILURE";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
export const SET_ITEMS_PER_PAGE = "SET_ITEMS_PER_PAGE";
